# Generated by Django 4.2.13 on 2024-05-29 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0005_alter_questtree_first_node_alter_questtree_last_node"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_quest_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_node",
                to="quest.questnode",
            ),
        ),
    ]
