# Generated by Django 4.2.13 on 2024-05-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(null=True),
        ),
    ]
