# Generated by Django 4.2.13 on 2024-06-01 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_user_current_quest_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="WouldYouRatherQA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now_add=True)),
                ("question", models.CharField(max_length=500)),
                ("choice_1", models.CharField(max_length=300)),
                ("choice_2", models.CharField(max_length=300)),
                ("answer", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_questioned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime_created"],
                "abstract": False,
            },
        ),
    ]
