# Generated by Django 4.2.13 on 2024-06-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_wouldyouratherqa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wouldyouratherqa",
            name="answer",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
