# Generated by Django 4.2.13 on 2024-06-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0007_langchainvars_questreviews_questnode_chain_and_more"),
        ("profiles", "0004_alter_wouldyouratherqa_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_langchain_config",
                to="quest.langchainvars",
            ),
        ),
    ]
