# Generated by Django 4.2.13 on 2024-05-17 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyUserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifyemail_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
