# Generated by Django 4.2.13 on 2024-05-28 23:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=2000)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NS", "Not Started"),
                            ("IP", "In Progress"),
                            ("F", "Finished"),
                            ("IC", "Incomplete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_low", models.IntegerField()),
                ("price_high", models.IntegerField()),
                ("optional", models.BooleanField(default=False)),
                ("next", models.ManyToManyField(to="quest.questnode")),
            ],
            options={
                "ordering": ["-datetime_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuestTree",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=10000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NS", "Not Started"),
                            ("IP", "In Progress"),
                            ("F", "Finished"),
                            ("IC", "Incomplete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("completion_exp", models.IntegerField()),
                ("price_low", models.IntegerField()),
                ("price_high", models.IntegerField()),
                (
                    "first_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_node",
                        to="quest.questnode",
                    ),
                ),
                (
                    "last_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_node",
                        to="quest.questnode",
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime_created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="questnode",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_tree",
                to="quest.questtree",
            ),
        ),
    ]
