# Generated by Django 4.2.13 on 2024-05-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questnode",
            name="next",
            field=models.ManyToManyField(blank=True, to="quest.questnode"),
        ),
    ]
