# Generated by Django 4.2.13 on 2024-05-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0003_alter_questnode_quest_alter_questtree_first_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questnode",
            name="completion_experience",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
