# Generated by Django 4.2.13 on 2024-05-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0004_questnode_completion_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questtree",
            name="first_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_node",
                to="quest.questnode",
            ),
        ),
        migrations.AlterField(
            model_name="questtree",
            name="last_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_node",
                to="quest.questnode",
            ),
        ),
    ]
