# Generated by Django 4.2.13 on 2024-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0005_alter_questtree_first_node_alter_questtree_last_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="questtree",
            name="location",
            field=models.CharField(default="East Lansing, MI, USA", max_length=200),
        ),
    ]
