# Generated by Django 4.2.13 on 2024-06-04 18:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quest", "0006_questtree_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="LangChainVars",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4", "gpt-4"),
                            ("gpt-4-turbo", "gpt-4-turbo"),
                            ("claude-3-sonnet-20240229", "claude-3"),
                            ("gemini-pro", "gemini-pro"),
                        ],
                        max_length=100,
                    ),
                ),
                ("max_tokens", models.IntegerField(default=2000)),
                ("system_prompt", models.TextField(max_length=300000)),
                (
                    "rag_docu_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "ordering": ["-datetime_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuestReviews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="langchain_config",
                        to="quest.langchainvars",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_reviewed",
                        to="quest.questnode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reviewing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime_created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="questnode",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node_langchain_config",
                to="quest.langchainvars",
            ),
        ),
        migrations.AddField(
            model_name="questtree",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tree_langchain_config",
                to="quest.langchainvars",
            ),
        ),
    ]
