# Generated by Django 4.2.13 on 2024-06-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0007_langchainvars_questreviews_questnode_chain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questreviews",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_reviewed",
                to="quest.questtree",
            ),
        ),
    ]
