# Generated by Django 4.2.13 on 2024-12-01 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quest', '0008_alter_questreviews_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationReviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(max_length=200)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langchain_config_location', to='quest.langchainvars')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_quest', to='quest.questtree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviewing_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
        ),
    ]
